spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/sb_mybatis?characterEncoding=utf-8&useSSL=false

logging:
  level:
    ROOT: INFO
    com:
      lsd: DEBUG
  file: E:/logs/mybatis.log

