spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/sb_mybatis?useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8

logging:
  level:
    ROOT: INFO
    cn:
      lsd: DEBUG
  file: E:/logs/mybatis.log

